### ISSUE TITLE
cocos.euclid.Vector2.__rsub__ bug 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [chaomodus/pyeuclid#5]
```
What steps will reproduce the problem?
1. in the python interpreter do
2. import euclid
3. a = euclid.Vector2(1,1)
4. (0,0) - a

What is the expected output? What do you see instead?
(-1.0, -1.0) is expected, you get
Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    (0,0)-a
  File "D:\tmp\euclid.py", line 202, in __rsub__
    return Vector2(other.x - self[0],
AttributeError: 'tuple' object has no attribute 'x'


What version of the product are you using? On what operating system?
euclid 0.31, python 2.6.1 , windows XP

Please provide any additional information below.
I think is a typo, with trivial fix (attached a svn diff against r31)


```

Original issue reported on code.google.com by `ccanepacc@gmail.com` on 18 Apr 2009 at 8:07

Attachments:
* [euclid_rsub_fix.txt](https://storage.googleapis.com/google-code-attachments/pyeuclid/issue-5/comment-0/euclid_rsub_fix.txt)

**Comment by chaomodus** [comment]
Patch applied.
